name: on-merge

on:
  push:
    branches:
    - 'master'

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  publish:
    timeout-minutes: 10
    if: |
      !contains(fromJson('["ci skip","skip ci"]'), github.event.head_commit.message) &&
      !startsWith(github.event.head_commit.message, 'docs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          commit: "chore: publish"
          title: "chore: publish"
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
